# Iris with KNN

In [1]:
import numpy as np
import sklearn
from sklearn import datasets
import matplotlib 
from matplotlib import pyplot as plt

In [2]:
iris = datasets.load_iris()

In [3]:
X_iris = iris['data']
Y_iris = iris['target']
X_iris[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
X_iris.shape

(150, 4)

In [5]:
Y_iris

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.neighbors import KNeighborsClassifier
#shuffle original dataset
np.random.seed(0)

indices = np.random.permutation(len(X_iris))

#train-test split
X_iris_train = X_iris[indices[:-10]]
Y_iris_train = Y_iris[indices[:-10]]
X_iris_test = X_iris[indices[-10:]]
Y_iris_test = Y_iris[indices[-10:]]

#create estimator
knn = KNeighborsClassifier()
knn.fit(X_iris_train, Y_iris_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [7]:
y_pred = knn.predict(X_iris_test)

print("predictions:", y_pred)

predictions: [1 2 1 0 0 0 2 1 2 0]


In [8]:
print("actual:", Y_iris_test)

actual: [1 1 1 0 0 0 2 1 2 0]


# Diabetes prediction with Linenar Regression

In [9]:
diabetes = datasets.load_diabetes()
X_diabets = diabetes['data']
Y_diabets = diabetes['target']
X_diabets[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [10]:
Y_diabets[:5]

array([151.,  75., 141., 206., 135.])

In [11]:
X_diabets.shape

(442, 10)

In [12]:
np.random.seed(0)
indices = np.random.permutation(X_diabets.shape[0])

#prepare dataset
X_diabets_train, Y_diabets_train = X_diabets[indices[:-20]], Y_diabets[indices[:-20]]
X_diabets_test, Y_diabets_test = X_diabets[indices[-20:]], Y_diabets[indices[-20:]]

#create estimator
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_diabets_train, Y_diabets_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
#print coef_
print("Coefficients: ", lin_reg.coef_)

Coefficients:  [  -3.78606011 -235.47377739  533.3485139   321.69200267 -827.89481203
  521.12370087  115.57077061  159.58767508  742.51130661   55.80177895]


In [14]:
y_pred = lin_reg.predict(X_diabets_test)
print("predictions: ", y_pred)

predictions:  [137.44785074 139.86211423 176.08047802  63.41903503  80.37300479
  74.28163679 153.74039144  94.71469624  87.1071867  116.23636198
 176.9443295  211.82147451 174.08795257 170.17742745 272.00732702
 209.68905565  93.82378084 230.48690313 109.25601606 220.11053015]


In [15]:
print("actual: ", Y_diabets_test)

actual:  [ 90. 116. 147.  43.  42.  48. 134.  84.  71.  64.  70. 310. 311. 122.
 243. 248.  91. 281. 142. 295.]


In [16]:
#show mean squared error
mse = np.mean((y_pred - Y_diabets_test)**2)
mse

3171.523799048002

# Try Ridge estomtors with various alphas

In [17]:
from sklearn.linear_model import Ridge
ridge = Ridge()
alphas = np.logspace(-4, -1, 6)
scores = [ ridge
         .set_params(alpha=alpha)
         .fit(X_diabets_train, Y_diabets_train)
         .score(X_diabets_test, Y_diabets_test)
         for alpha in alphas]
print ("scores: ", scores)

scores:  [0.6378307680594713, 0.6380314369658577, 0.6386096901762819, 0.6392864424885626, 0.63777543863284, 0.6289069163063801]


# Sparsity

In [18]:
from sklearn.linear_model import Lasso
lasso = Lasso()
lasso_scores = [lasso
                .set_params(alpha=alpha)
                .fit(X_diabets_train, Y_diabets_train)
                .score(X_diabets_test, Y_diabets_test)
                for alpha in alphas]
best_alpha = alphas[np.argmax(lasso_scores)]

lasso.set_params(alpha=best_alpha)
lasso.fit(X_diabets_train, Y_diabets_train)

Lasso(alpha=0.00630957344480193, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [19]:
#some coef will be set to zero
lasso.coef_

array([  -0.        , -227.72554353,  536.72020432,  317.27069098,
       -514.59145695,  268.92040211,  -15.54729202,  126.27470261,
        626.19510226,   54.40682473])

# Iris Classification with Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression
df = datasets.load_iris()
X = df['data']
Y = df['target']

test_size = int(np.ceil(len(X) * 0.1))
indices = np.random.permutation(len(X))
X_train = X[:-test_size]
Y_train = Y[:-test_size]
X_test = X[-test_size:]
Y_test = Y[-test_size:]

log_clf = LogisticRegression(multi_class='multinomial', solver='lbfgs')

log_clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
log_clf.predict(X_test)

array([2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Support vector machines (SVMs)

In [22]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
svc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [23]:
kernels = ['linear', 'poly', 'rbf']
scores = [svc
          .set_params(kernel=kernel) 
          .fit(X_train, Y_train)
          .score(X_test, Y_test)
          for kernel in kernels]

/Users/80151/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/80151/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [24]:
scores

[0.9333333333333333, 1.0, 0.9333333333333333]